# Generated by Django 2.2 on 2019-04-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_auto_20190428_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='holiday',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
