# Generated by Django 2.2 on 2019-04-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0005_auto_20190429_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
